[workspace]
channels = ["conda-forge"]
name = "geo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
rasterio = ">=1.4.3,<2"
numpy = ">=2.3.5,<3"
rerun-sdk = ">=0.27.2,<0.28"
matplotlib = ">=3.10.8,<4"
